# Dotbro's configuration file.
# See: https://github.com/hypnoglow/dotbro#configuration
# Note that you can use $ENV_VARIABLE in paths.

[directories]

dotfiles = "$HOME/Developer/github.com/hypnoglow/dotfiles"
destination = "$HOME"
backup = "$HOME/.dotfiles~"

[mapping]

"bin" = "bin"

"shell/libraries" = ".sh"
"shell/profile.d" = ".profile.d"
"shell/profile" = ".profile"

"bash/bashenv" = ".bash_env"

"zsh/lib" = ".zsh/lib"
"zsh/zprofile" = ".zprofile"
"zsh/zshrc" = ".zshrc"
"zsh/zimrc" = ".zimrc"
"zsh/zlogin" = ".zlogin"
"zsh/zshenv" = ".zshenv"
"zsh/zshrc.d" = ".zshrc.d"

"vim/vimrc" = ".vimrc"

"neovim/init.vim" = ".config/nvim/init.vim"
"neovim/ftplugin/yaml.vim" = ".config/nvim/ftplugin/yaml.vim"

"git/gitconfig_macos" = ".gitconfig"
"git/gitconfig_base" = ".gitconfig_base"
"git/gitcommit" = ".gitcommit"
"git/gitexcludes" = ".gitexcludes"
"git/hooks" = ".githooks"

"lazygit/config.yml" = "Library/Application Support/lazygit/config.yml"

"bat/config" = ".config/bat/config"
"starship.toml" = ".config/starship.toml"
"television/k8s.toml" = ".config/television/cable/k8s.toml"
"television/projects.toml" = ".config/television/cable/projects.toml"

"karabiner/complex_modifications/" = ".config/karabiner/assets/complex_modifications/"
"ghostty/config" = "Library/Application Support/com.mitchellh.ghostty/config"

"zed/settings.json" = ".config/zed/settings.json"
"zed/keymap.json" = ".config/zed/keymap.json"
"zed/tasks.json" = ".config/zed/tasks.json"
