[character]
symbol = "λ"
style_success = "bold fg:202"

[directory]
style = "bold fg:99"

[git_branch]
style = "bold fg:213"

[git_status]
style = "bold fg:226"
show_sync_count = true

[golang]
disabled = true

[kubernetes]
symbol = "⎈ "
style = "fg:#3371e3"
disabled = true
