# Dotbro's configuration file.
# See: https://github.com/hypnoglow/dotbro#configuration
# Note that you can use $ENV_VARIABLE in paths.

[directories]

dotfiles = "$HOME/code/github.com/hypnoglow/dotfiles"
destination = "$HOME"
backup = "$HOME/.dotfiles~"

[mapping]

"bin" = "bin"

"shell/libraries" = ".sh"
"shell/profile.d" = ".profile.d"
"shell/profile" = ".profile"

"bash/bashenv" = ".bash_env"
"bash/env" = ".bash/env"

"zsh/lib" = ".zsh/lib"
"zsh/zprofile" = ".zprofile"
"zsh/zshrc" = ".zshrc"
"zsh/zimrc" = ".zimrc"
"zsh/zlogin" = ".zlogin"
"zsh/zshenv" = ".zshenv"
"zsh/zshrc.d" = ".zshrc.d"

"vim/vimrc" = ".vimrc"

"neovim/init.vim" = ".config/nvim/init.vim"
"neovim/ftplugin/yaml.vim" = ".config/nvim/ftplugin/yaml.vim"

"git/gitconfig_macos" = ".gitconfig"
"git/gitconfig_base" = ".gitconfig_base"
"git/gitcommit" = ".gitcommit"
"profiles/antares/git/gitexcludes" = ".gitexcludes"
"git/hooks" = ".githooks"

"lazygit/config.yml" = "Library/Application Support/lazygit/config.custom.yml"

"profiles/antares/karabiner" = ".config/karabiner"
"starship.toml" = ".config/starship.toml"
"usql/config.yaml" = "Library/Application Support/usql/config.yaml"
"ghostty/config" = "Library/Application Support/com.mitchellh.ghostty/config"
